Implement Mailchimp backup
OCHA-DAP/hdx-signals pull request #196
Opened 2024-07-02 13:58 UTC by caldwellst

Addresses #101.

2024-07-02 19:04 UTC, hannahker requested changes
Looks good! I would just suggest putting the script under `src/email/mailchimp`, since I think that directory is a good fit and we don't need to add any new directories.

2024-07-03 09:54 UTC, caldwellst commented
Alright, moved under `email/mailchimp`!

2024-07-03 14:40 UTC, hannahker commented on README.md
> +- runs: Scripts for actual runs, called in `.github` workflows.
Can remove this now!

2024-07-03 14:41 UTC, hannahker approved these changes
Looks great! Just see the comment to update the `README`, then should be good to merge.

2024-07-03 14:44 UTC, caldwellst commented on README.md
> +- runs: Scripts for actual runs, called in `.github` workflows.
Doh! Good catch.

2024-07-03 14:46 UTC, merged